CREATE USER 
'futbol'@'localhost' 
IDENTIFIED  BY 'Futbol2526$';

GRANT USAGE ON *.* TO 'futbol'@'localhost';

ALTER USER 'futbol'@'localhost' 
REQUIRE NONE 
WITH MAX_QUERIES_PER_HOUR 0 
MAX_CONNECTIONS_PER_HOUR 0 
MAX_UPDATES_PER_HOUR 0 
MAX_USER_CONNECTIONS 0;


GRANT ALL PRIVILEGES ON futbol.* 
TO 'futbol'@'localhost';

FLUSH PRIVILEGES;
